### ISSUE TITLE
CreateProductionMaster - obscure error message when private key does not have access to content types and/or libraries

### ISSUE THREAD

**Issue by eponymous301** [eluv-io/elv-client-js#130]
Use case: There is an account that is added to an access group to temporarily allow ingests, then removed from access group afterwards for security reasons. When outside group, the account cannot see anything - no libraries, content types, etc.

If tenant admin forgets to add this ingest account to the group, then ingest operator tries to create a Production Master, the  CreateProductionMaster() call fails with an obscure error, `createContent failed - Log not present in transaction`.  Clearer would be something like "access denied" or "library not found" / "content type not found"

Stack trace:

```
Error: createContent failed - Log not present in transaction
    at EthClient.DeployDependentContract (.../node_modules/@eluvio/elv-client-js/src/EthClient.js:398:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AuthorizationClient.CreateContentObject (.../node_modules/@eluvio/elv-client-js/src/AuthorizationClient.js:1116:48)
    at async ElvClient.exports.CreateContentObject (.../node_modules/@eluvio/elv-client-js/src/client/ContentManagement.js:567:33)
    at async ElvClient.exports.CreateProductionMaster (.../node_modules/@eluvio/elv-client-js/src/client/ABRPublishing.js:82:29)
```

Throw statement:
```
  async DeployDependentContract({
    contractAddress,
    methodName,
    args=[],
    eventName,
    eventValue
  }) {
    const abi = await this.client.ContractAbi({contractAddress});
    const event = await this.CallContractMethodAndWait({contractAddress, abi, methodName, methodArgs: args});
    const eventLog = this.ExtractEventFromLogs({abi, event, eventName, eventValue});

    if(!eventLog) {
      throw Error(`${methodName} failed - Log not present in transaction`);
    }
```

**Comment by elv-zenia** [comment]
This issue addresses an issue with contract calls being made when the current account has no contribute permission. The above PR catches the aforementioned error earlier (checking for permissions) and throws a clearer error message.
